apiVersion: v1
kind: Namespace
metadata:
  name: drift-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: drift-test
  labels:
    app: backend-api
    tier: critical
    monitor: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
        tier: critical
    spec:
      containers:
      - name: backend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: drift-test
  labels:
    app: frontend-web
    tier: critical
    monitor: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
        tier: critical
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: drift-test
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: drift-test
spec:
  selector:
    app: frontend-web
  ports:
  - port: 80
    targetPort: 80