apiVersion: v1
kind: Service
metadata:
  name: cost-optimizer-dashboard
  namespace: devops-apps
  labels:
    app: cost-optimizer
    component: dashboard
spec:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 8081
    targetPort: dashboard
    protocol: TCP
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  selector:
    app: cost-optimizer
---
apiVersion: v1
kind: Service
metadata:
  name: cost-optimizer-health
  namespace: devops-apps
  labels:
    app: cost-optimizer
    component: health
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  selector:
    app: cost-optimizer