apiVersion: v1
kind: Service
metadata:
  name: drift-detector
  namespace: devops-apps
  labels:
    app: drift-detector
    component: devops-app
spec:
  selector:
    app: drift-detector
  ports:
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP