apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detector
  namespace: devops-apps
  labels:
    app: drift-detector
    component: devops-app
    tier: critical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-detector
  template:
    metadata:
      labels:
        app: drift-detector
        component: devops-app
        tier: critical
    spec:
      serviceAccountName: drift-detector
      containers:
      - name: drift-detector
        image: ghcr.io/monadic/drift-detector:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: drift-detector-secrets
              key: cub-token
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: drift-detector-secrets
              key: claude-api-key
              optional: true
        - name: CUB_API_URL
          value: "https://api.confighub.com/v1"
        - name: CUB_SPACE
          value: "drift-detector"
        - name: AUTO_FIX
          value: "true"
        - name: RUN_INTERVAL
          value: "5m"
        ports:
        - containerPort: 8080
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"