apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: drift-test
  labels:
    app: test-app
    tier: standard
    monitor: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        tier: standard
    spec:
      containers:
      - name: test-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"