apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: default
  labels:
    app: redis
    tier: cache
    cost-category: memory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: cache
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
