apiVersion: v1
kind: Namespace
metadata:
  name: devops-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detector-flux
  namespace: devops-apps
  labels:
    app: drift-detector-flux
    type: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-detector-flux
  template:
    metadata:
      labels:
        app: drift-detector-flux
        type: devops-app
    spec:
      serviceAccountName: drift-detector-flux
      containers:
      - name: drift-detector-flux
        image: drift-detector-flux:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: FLUX_NAMESPACE
          value: "flux-system"
        - name: CUB_API_URL
          value: "https://hub.confighub.com/api/v1"
        - name: CUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: drift-detector-secrets
              key: cub-token
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: drift-detector-secrets
              key: claude-api-key
        - name: AUTO_FIX
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep drift-detector-flux | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-detector-flux
  namespace: devops-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drift-detector-flux
rules:
# Read Flux CRDs
- apiGroups: ["kustomize.toolkit.fluxcd.io"]
  resources: ["kustomizations"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["gitrepositories", "helmrepositories", "buckets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["notification.toolkit.fluxcd.io"]
  resources: ["alerts", "providers", "receivers"]
  verbs: ["get", "list"]
# Read general resources for comparison
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drift-detector-flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drift-detector-flux
subjects:
- kind: ServiceAccount
  name: drift-detector-flux
  namespace: devops-apps
---
apiVersion: v1
kind: Secret
metadata:
  name: drift-detector-secrets
  namespace: devops-apps
type: Opaque
stringData:
  cub-token: "your-cub-token-here"
  claude-api-key: "your-claude-api-key-here"